### ISSUE TITLE
sincerely ask for your advice!

### ISSUE THREAD

**Issue by zhaoweifeng-sys** [StevenLamontagne/EVChargingStationModel#1]
Dear Mr. Steven, Hello! I am a graduate student. Your project has inspired me a lot, but I found that the project lacks the necessary data for program operation. Can you send me a copy? My email is: zwf_chd@163com.Thank you very much for reading this question in your busy schedule and look forward to your reply.

**Comment by StevenLamontagne** [comment]
Hello!

I am happy to hear that this work has inspired you! If I may ask, how did you find this work? The associated article has not yet been released, though it should be ready soon. Once it is ready to submit, I'd be happy to send along the data (as well as a link for the working paper on arXiv, if you would like).

In the meantime, if you would like to generate data for trying out the code, this can be done by running the following code via your Python IDE of choice (assuming paths for all of the data has not been modified):

```
from MaximumCover_Data import Data_MaximumCover
from MaximumCover_Model import Model_MaximumCover
from docplex.mp.model import Model

mdl = Model()
Data = Data_MaximumCover( userFilepath = "Data/StationsAndClasses/UserClasses_Simple.json", stationFilepath = "Data/StationsAndClasses/Stations_Simple.json")
solver = Model_MaximumCover(mdl, Data)
```

All of the heuristic methods use the `Data_MaximumCover` class for their data, though the GrowthFunction and SingleLevel models have their own data classes.

**Comment by zhaoweifeng-sys** [comment]
> Hello!
> 
> I am happy to hear that this work has inspired you! If I may ask, how did you find this work? The associated article has not yet been released, though it should be ready soon. Once it is ready to submit, I'd be happy to send along the data (as well as a link for the working paper on arXiv, if you would like).
> 
> In the meantime, if you would like to generate data for trying out the code, this can be done by running the following code via your Python IDE of choice (assuming paths for all of the data has not been modified):
> 
> ```
> from MaximumCover_Data import Data_MaximumCover
> from MaximumCover_Model import Model_MaximumCover
> from docplex.mp.model import Model
> 
> mdl = Model()
> Data = Data_MaximumCover( userFilepath = "Data/StationsAndClasses/UserClasses_Simple.json", stationFilepath = "Data/StationsAndClasses/Stations_Simple.json")
> solver = Model_MaximumCover(mdl, Data)
> ```
> 
> All of the heuristic methods use the `Data_MaximumCover` class for their data, though the GrowthFunction and SingleLevel models have their own data classes.

Thank you for your reply and look forward to your working paper on arXiv，I can't wait to read it！

**Comment by zhaoweifeng-sys** [comment]
> Dear Mr. Steven, Hello! I have read your article updated in arXiv a few days ago. I was looking forward to your research results a long time ago, and now it has finally been published. To be honest, your idea is great! In order to better understand your research results, can you provide me with the test data that has not been uploaded? My email is: zwf_chd@163com. I will carefully study your research results. If I have some other ideas, I will also communicate with you at any time.
