### ISSUE TITLE
Sincerely ask you for help！

### ISSUE THREAD

**Issue by zhaoweifeng-sys** [StevenLamontagne/EVChargingStationModel#4]
Dear Mr. Steven, Hello! I have read your article updated in arXiv a few days ago. I was looking forward to your research results a long time ago, and now it has finally been published. To be honest, your idea is great! In order to better understand your research results, can you provide me with the test data that has not been uploaded? My email is: zwf_chd@163com. I will carefully study your research results. If I have some other ideas, I will also communicate with you at any time.

**Comment by StevenLamontagne** [comment]
Hello!

It will be my pleasure to send along the data. The file sizes are quite large (varying in size from 10MB per instance for the Simple dataset up to 1.5 GB per instance for the LongSpan dataset), and so doubt I will be able to  send them directly via email. I will coordinate with you via email to determine the best way to transfer them.

**Comment by zhaoweifeng-sys** [comment]
Do you use Google drive? I think you can share them with me through Google drive.My Google account is：feng zhao ; registered email ***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StevenLamontagne/EVChargingStationModel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StevenLamontagne/EVChargingStationModel] Sincerely ask you for help！ (Issue #4)





 
Hello!
 
It will be my pleasure to send along the data. The file sizes are quite large (varying in size from 10MB per instance for the Simple dataset up to 1.5 GB per instance for the LongSpan dataset), and so doubt I will be able to  send them directly via email. I will coordinate with you via email to determine the best way to transfer them.

**Comment by StevenLamontagne** [comment]
Could you send me an email from the correct address? I get a warning for an invalid email address. My email is steven.lamontagne@umontreal.ca .

**Comment by zhaoweifeng-sys** [comment]
Hello, my email ***@***.***
Thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StevenLamontagne/EVChargingStationModel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 晚上10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StevenLamontagne/EVChargingStationModel] Sincerely ask you for help！ (Issue #4)





 
Could you send me an email from the correct address? I get a warning for an invalid email address. My email is ***@***.*** .

**Comment by StevenLamontagne** [comment]
![image](https://user-images.githubusercontent.com/97698656/177361507-fda7c4e9-dcf0-42e1-9a71-6afc8f3d61eb.png)

It appears that GitHub is censoring the email address, and so I can't see the email to send to it. If the same is the case for you in my above message, my email address is the one linked in the submission history page of the arXiv paper. Hopefully this link should work for direct access to the email address: https://arxiv.org/show-email/71ebe4ed/2206.11165 , otherwise you can check the arXiv page.
